spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: bookstore
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
